global:
  minio:
    enabled: false
  appConfig:
    object_store:
      enabled: true
      connection:
        # Use the built-in local storage instead of S3/Minio
        provider: local
        local:
          path: /var/opt/gitlab/gitlab-rails/shared/artifacts
    artifacts:
      bucket: gitlab-artifacts
    lfs:
      bucket: gitlab-lfs
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    externalDiffs:
      bucket: gitlab-mr-diffs
    terraformState:
      bucket: gitlab-terraform-state
    dependencyProxy:
      bucket: gitlab-dependency-proxy
    pagesObjectStore:
      bucket: gitlab-pages

# Create a secret for registry storage configuration
registry:
  enabled: true
  storage:
    secret: gitlab-registry-storage
    key: storage
