## GitLab Minimal Configuration - gitlab-values.yaml

global:
  hosts:
    domain: agrishakov.com  # Your domain from the existing config
    https: true
  
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

  # Required secrets for core functionality
  gitaly:
    authToken:
      secret: gitlab-gitaly-secret
      key: token
  shell:
    authToken:
      secret: gitlab-shell-secret
      key: secret
  rails:
    secret:
      secret: gitlab-rails-secret
  workhorse:
    secret:
      secret: gitlab-workhorse-secret
      key: shared-secret
  
  # Disable email by default (can be configured later)
  email:
    enabled: false
  
  # Disable MinIO (object storage)
  minio:
    enabled: false

  # Database connection
  psql:
    password:
      secret: gitlab-postgresql-password
      key: password
      
  # Disable all object storage features
  appConfig:
    lfs:
      enabled: false
    artifacts:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    externalDiffs:
      enabled: false
    terraformState:
      enabled: false
    dependencyProxy:
      enabled: false
    pages:
      enabled: false

## Persistence configuration to use existing PVCs
postgresql:
  persistence:
    existingClaim: postgresql-data
    storageClass: local-storage

redis:
  persistence:
    existingClaim: redis-data
    storageClass: local-storage

gitaly:
  persistence:
    existingClaim: gitaly-data
    storageClass: local-storage

prometheus:
  server:
    persistentVolume:
      existingClaim: prometheus-data
      storageClass: local-storage

# Main UI configuration - keep minimal but functional
webservice:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 800Mi
    limits:
      cpu: 1
      memory: 1.5Gi

# Disable registry as requested
registry:
  enabled: false

# Sidekiq for essential background jobs
gitlab-sidekiq:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 600Mi
    limits:
      cpu: 800m
      memory: 1Gi

# Keep toolbox for backups and maintenance
toolbox:
  enabled: true
  backups:
    objectStorage:
      enabled: false

# Disable runners as requested
gitlab-runner:
  install: false

# Disable the built-in NGINX ingress controller since you're using Traefik
nginx-ingress:
  enabled: false

# Custom ingress configuration to work with Traefik
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # Add any Traefik-specific annotations here if needed
    # traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  configureCertmanager: false  # Set to true if you want cert-manager integration

# Keep certmanager for HTTPS
certmanager:
  install: true
  email: grishalmax@gmail.com

certmanager-issuer:
  email: grishalmax@gmail.com

# Make sure migrations run successfully
migrations:
  enabled: true
