# kubectl apply -f gitlab-tls-certificate.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
  namespace: gitlab-production
spec:
  secretName: gitlab-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gitlab.agrishakov.com
  dnsNames:
    - gitlab.agrishakov.com

